org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
fabric.loom.disableObfuscation=true

minecraft_version=26.2

# Fabric
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version=0.153.0+26.2

# NeoForge
neoforge_version=26.2.0.36-beta
moddevgradle_version=2.0.143

mod_version=0.1.0
maven_group=dev.comfyfluffy.caustica
archives_base_name=caustica
