modLoader = "javafml"
loaderVersion = "[1,)"
license = "LGPL-3.0-or-later"

[[mods]]
modId = "fluorite"
version = "${version}"
displayName = "Fluorite"
description = '''Hardware-ray-traced renderer with DLSS Ray Reconstruction for the Minecraft Vulkan backend.'''
authors = "Yuhan YAN (DsWePm), ComfyFluffy and Caustica contributors"

[[mixins]]
config = "fluorite-common.mixins.json"

[[mixins]]
config = "fluorite-neoforge.mixins.json"

[[dependencies.fluorite]]
modId = "neoforge"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.fluorite]]
modId = "minecraft"
type = "required"
versionRange = "[26.2,)"
ordering = "NONE"
side = "CLIENT"
